# Generated by Django 4.2.5 on 2023-09-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0002_alter_joblist_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblist",
            name="job_description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
