# Generated by Django 4.2.5 on 2023-09-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0003_alter_joblist_job_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joblist", old_name="Job_image", new_name="job_image",
        ),
    ]
