# Generated by Django 4.2.5 on 2023-09-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0004_rename_job_image_joblist_job_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applyjob", old_name="job", new_name="job_role",
        ),
    ]
