# Generated by Django 4.2.5 on 2023-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0005_rename_job_applyjob_job_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="address",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
