# Generated by Django 4.2.5 on 2023-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0006_applyjob_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="diversityinfo",
            name="preference",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
