# Generated by Django 4.2.5 on 2023-09-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0007_diversityinfo_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="diversityinfo",
            name="email",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
