# Generated by Django 4.2.5 on 2023-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0009_alter_diversityinfo_preference"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdMeCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=500)),
                ("code", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name_plural": "IdMe Credentials",
                "db_table": "IdMe Credentials",
            },
        ),
    ]
