# Generated by Django 4.2.5 on 2023-09-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0010_idmecredentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idmecredentials",
            name="code",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="idmecredentials",
            name="user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
