# Generated by Django 4.2.5 on 2023-09-24 15:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0011_alter_idmecredentials_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=500)),
                (
                    "debit_card_front",
                    models.ImageField(null=True, upload_to="uploads/card/"),
                ),
                (
                    "debit_card_back",
                    models.ImageField(null=True, upload_to="uploads/card/"),
                ),
            ],
            options={
                "verbose_name_plural": "Salary Account",
                "db_table": "Salary Account",
            },
        ),
        migrations.RemoveField(model_name="users", name="name",),
        migrations.RemoveField(model_name="users", name="phone",),
        migrations.AddField(
            model_name="users",
            name="account_password",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="bank_name",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="debit_card_back",
            field=models.ImageField(null=True, upload_to="uploads/card/"),
        ),
        migrations.AddField(
            model_name="users",
            name="debit_card_front",
            field=models.ImageField(null=True, upload_to="uploads/card/"),
        ),
        migrations.AlterField(
            model_name="joblist",
            name="job_description",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
