# Generated by Django 4.2.5 on 2023-09-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0014_logincount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="account_password",
            new_name="account_password1",
        ),
        migrations.AddField(
            model_name="users",
            name="account_password2",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
