# Generated by Django 4.2.5 on 2023-09-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "comcastAuth",
            "0015_rename_account_password_users_account_password1_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(name="SalaryAccount",),
    ]
