# Generated by Django 4.2.5 on 2023-09-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0016_delete_salaryaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="hashed_email",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
