# Generated by Django 4.2.5 on 2023-09-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0017_applyjob_hashed_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Personality Checks",
                "db_table": "Personality Check",
            },
        ),
    ]
