# Generated by Django 4.2.5 on 2023-10-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0018_personalitycheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("bank_name", models.CharField(max_length=200)),
                ("account_type", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=100)),
                ("routing_number", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Financial Info",
                "db_table": "Financial Info",
            },
        ),
    ]
