# Generated by Django 4.2.5 on 2023-10-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comcastAuth", "0019_financialinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Bank Names", "db_table": "Bank Name",},
        ),
    ]
